

POST http://localhost:3000/auth/signup
content-Type: application/json
{
  "email":"machadofelipe2016@outlook.com",
  "password":"feafsdfds"
}


//GET http://localhost:3000/

//GET http://localhost:3000/auth
